apiVersion: v2
name: automation-hub
description: A Helm chart for automation-hub

# A chart can be either an 'application' or a 'library' chart.
type: application

# Chart version
version: 0.1.0

# Application version
appVersion: "1.0.0"