apiVersion: v1
kind: Service
metadata:
  name: {{ include "automation-hub.fullname" . }}
  namespace: {{ .Release.Namespace | default "automation-hub" }}
  labels:
    {{- include "automation-hub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.type }}
  ports:
    - port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
      {{- if and (eq .Values.type "NodePort") .Values.nodePort }}
      nodePort: {{ .Values.nodePort }}
      {{- end }}
  selector:
    {{- include "automation-hub.selectorLabels" . | nindent 4 }}