apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "automation-hub.fullname" . }}-worker-rolebinding
  namespace: {{ .Release.Namespace | default "automation-hub" }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "automation-hub.fullname" . }}-worker-role
subjects:
- kind: ServiceAccount
  name: {{ include "automation-hub.fullname" . }}-worker-sa
  namespace: {{ .Release.Namespace | default "automation-hub" }}