name   名字   名称：Docker Image CI: Docker Image CI

on   :   在:
  push   推动:   推:
    branches   branches   分支机构: [ "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main" ]: [ "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main" ]
  pull_request:
    branches   branches   分支机构: [ "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main" ]: [ "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main"   "main" ]

jobs   工作:   工作:

  build   构建:   构建:

    runs-on   上运行:ubuntu-latest   运行在: ubuntu-latest

    steps   步骤:   步骤:
    - —用途：actions/checkout@v4uses: actions/checkout@v4
    - -名称：构建Docker镜像name   名字: Build the Docker image
      run   运行运行docker build命令。——file Dockerfile——tag my-image-name:$（日期%s）: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
